# Generated by Django 5.0.1 on 2024-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_alter_user_id_bid_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='element',
            field=models.CharField(default='default_value', max_length=20),
        ),
    ]
