# Generated by Django 5.0.1 on 2024-11-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctionlisting_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='element',
            field=models.CharField(max_length=20),
        ),
    ]
