# Generated by Django 5.0.1 on 2024-11-24 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_price_auctionlisting_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
